### ISSUE TITLE
Logout after logged in

### ISSUE THREAD

**Issue by 2peter3** [JosiahSayers/shrtlnk#34]
Hey, 
I have signed up at [shrtlnk.dev](https://shrtlnk.dev/) and tried to login in - it works, but after a click on any page im logged out. Do you have any ideas?

**Comment by JosiahSayers** [comment]
Hey, sorry for the response delay! I'm not able to replicate this in Chrome. Would you be able to try clearing cookies and logging in again?

**Comment by JosiahSayers** [comment]
I poked around a little longer and found a really weird edge case. The should be fixed by #46 and deployed now. 

Thanks for reporting and feel free to comment again if you encounter any other issues/feature requests!
